INSERT INTO hero (superHeroName, realName, universe, power)
VALUES  ('Spiderman', 'Peter Parker', 'Marvel', 'Spider Sense'),
        ('Superman', 'Clark Kent', 'DC', 'Kryptonian'),
        ('Batman', 'Bruce Wayne', 'DC', 'Intelligence'),
        ('Wonder Woman', 'Diana Prince', 'DC', 'Amazonian'),
        ('Iron Man', 'Tony Stark', 'Marvel', 'Suit'),
        ('Captain America', 'Steve Rogers', 'Marvel', 'Super Soldier'),
        ('Black Widow', 'Natasha Romanoff', 'Marvel', 'Spy'),
        ('Hulk', 'Bruce Banner', 'Marvel', 'Strength'),
        ('Thor', 'Thor Odinson', 'Marvel', 'Asgardian'),
        ('Green Lantern', 'Hal Jordan', 'DC', 'Power Ring'),
        ('Flash', 'Barry Allen', 'DC', 'Speed'),
        ('Aquaman', 'Arthur Curry', 'DC', 'Atlantean'),
        ('Hawkeye', 'Clint Barton', 'Marvel', 'Marksmanship'),
        ('Cyborg', 'Victor Stone', 'DC', 'Cybernetic Enhancement'),
        ('Martian Manhunter', 'J''onn J''onzz', 'DC', 'Martian'),
        ('Black Panther', 'T''Challa', 'Marvel', 'Enhanced Senses'),
        ('Vision', 'Vision', 'Marvel', 'Density Control'),
        ('Scarlet Witch', 'Wanda Maximoff', 'Marvel', 'Chaos Magic'),
        ('Doctor Strange', 'Stephen Strange', 'Marvel', 'Sorcerer Supreme'),
        ('Ant-Man', 'Scott Lang', 'Marvel', 'Size Alteration'),
        ('Wasp', 'Hope van Dyne', 'Marvel', 'Size Alteration'),
        ('Black Canary', 'Dinah Lance', 'DC', 'Canary Cry'),
        ('Green Arrow', 'Oliver Queen', 'DC', 'Marksmanship'),
        ('Supergirl', 'Kara Zor-El', 'DC', 'Kryptonian'),
        ('Daredevil', 'Matt Murdock', 'Marvel', 'Enhanced Senses'),
        ('Punisher', 'Frank Castle', 'Marvel', 'Marksmanship'),
        ('Jessica Jones', 'Jessica Jones', 'Marvel', 'Super Strength'),
        ('Luke Cage', 'Luke Cage', 'Marvel', 'Super Strength'),
        ('Iron Fist', 'Danny Rand', 'Marvel', 'Chi Manipulation'),
        ('Star-Lord', 'Peter Quill', 'Marvel', 'Marksmanship'),
        ('Gamora', 'Gamora', 'Marvel', 'Assassin'),
        ('Rocket Raccoon', 'Rocket', 'Marvel', 'Marksmanship'),
        ('Groot', 'Groot', 'Marvel', 'Regeneration'),
        ('Drax the Destroyer', 'Drax', 'Marvel', 'Strength'),
        ('Mantis', 'Mantis', 'Marvel', 'Empathy'),
        ('Nebula', 'Nebula', 'Marvel', 'Cybernetic Enhancement'),
        ('Yondu', 'Yondu Udonta', 'Marvel', 'Yaka Arrow Control'),
        ('Shazam', 'Billy Batson', 'DC', 'Magic'),
        ('Black Adam', 'Teth-Adam', 'DC', 'Magic'),
        ('Hawkman', 'Carter Hall', 'DC', 'Reincarnation'),
        ('Hawkgirl', 'Shiera Hall', 'DC', 'Reincarnation'),
        ('Zatanna', 'Zatanna Zatara', 'DC', 'Magic'),
        ('John Constantine', 'John Constantine', 'DC', 'Magic'),
        ('Swamp Thing', 'Alec Holland', 'DC', 'Elemental Control'),
        ('Deadman', 'Boston Brand', 'DC', 'Spirit'),
        ('Spectre', 'Jim Corrigan', 'DC', 'Spirit'),
        ('Etrigan the Demon', 'Jason Blood', 'DC', 'Demon'),
        ('Raven', 'Rachel Roth', 'DC', 'Empathy'),
        ('Starfire', 'Koriand''r', 'DC', 'Energy Projection'),
        ('Beast Boy', 'Garfield Logan', 'DC', 'Shape Shifting');

INSERT INTO userApi (username, password, role)
VALUES  ('davidmacar', '$2a$10$HckVmtH0/ks6V5FjHP/5k.lxwuy3tR94UCAapq3lUbFqG7ksYiqHe', 'USER');
